algoritmo "10a0"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Descrição   : Conta de 10 a 0
// Autor(a)    : Victor Antônio Gomes
// Data atual  : 16/01/2025
var

teste: caractere
    contador: Inteiro
inicio
    contador <- 10
    Enquanto (contador >= 0) faca
            Escreval(contador)
            contador <- contador - 1
    FimEnquanto
    Escreval("Terminei de contar")
fimalgoritmo