algoritmo "0a10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Gustavo Guanabara]
// Descrição   : Conta de 0 a 10
// Autor(a)    : Victor Antônio Gomes
// Data atual  : 16/01/2025
var
    contador: Inteiro
inicio
    contador <- 0
    Enquanto (contador < 10) faca
            Escreval(contador)
            contador <- contador + 1
    FimEnquanto
    Escreval("Terminei de contar")
fimalgoritmo